version: '3.8'

services:
  user_db:
    extends:
      file: user_and_auth_microservice/docker-compose.user_and_auth_microservice.yml
      service: user_db

  user_and_auth_microservice:
    extends:
      file: user_and_auth_microservice/docker-compose.user_and_auth_microservice.yml
      service: user_and_auth_microservice

volumes:
  user_db_data:
