spring:
  application:
    name: gateway_microservice

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://user-and-auth-microservice:8081
        predicates:
        - Path=/api/user/**
        
logging:
  level:
    org:
      springframework:
        security: DEBUG


server:
  port: 8080
