version: '3.8'

services:
  gateway_microservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gateway-microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_JACKSON_TIME_ZONE=Europe/Berlin
      - SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS=false
      - JWT_SECRET=super_secret
    # REMOVE VOLUMES FOR PRODUCTION
    volumes: 
      - .:/app

