version: '3.8'

services:
  compressing_microservice:
    build: .
    container_name: compressing-microservice
    volumes:
      - shared_data:/shared_data
      # Remove for production
      - ./app:/app
    ports:
      - 8082:8082
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:alpine"
    container_name: compressing-microservice-redis

  celery:
    build: .
    command: celery -A service.tasks worker --loglevel=info
    container_name: compressing-microservice-celery
    volumes:
      - shared_data:/shared_data
      # Remove for production
      - ./app:/app
    depends_on:
      - redis

volumes:
  shared_data:
